### PR TITLE
SSCCE for issue #11183

### PR DESCRIPTION
**Pull request by fboechats**
refs #11183

### CODE REVIEW

**Comment by papb** [comment]
It's not working, it seems you just copy-pasted the code in the issue but it's not valid javascript and has some weird stuff such as `await user.createdAt` which doesn't make sense :)

**Comment by fboechats** [comment]
Well... You are right, I copy pasted. Sorry, I thought it was supposed to do that.

**Comment by papb** [comment]
@fboechats What I wanted is a working SSCCE, you can start with the that code but it needs a few tweaks. Perhaps you can take a look at the other SSCCEs here to see how they did it. Let me know if you have more questions :)

**Comment by papb** [comment]
Actually don't worry about it, I found that 11183 was actually a duplicate of 3759, and that other issue has a lot of useful code already, so this is no longer necessary :) Thanks for your time anyway :+1:

**Comment by fboechats** [comment]
Ok, yesterday I was really busy, sorry for not been able to provide a good SSCCE.

**Comment by papb** [comment]
Don't worry about it :) Thanks for the help so far!! Hope to see you around :)

**Pull request closed without merging**
